extends@: default
child_type: item

rules:
  slug:
    pattern: "[a-z][a-z0-9_\-]+"
    min: 2
    max: 80

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        layout:
          type: tab
          title: Layout Settings

          fields:

            content_title:
              type: spacer
              title: Layout Settings

            header.sidebarlayout:
              type: select
              label: Sidebar Layout
              default: global
              options:
                global: 'Use theme setting'
                sidebar-top: 'Sidebar Top'
                sidebar-bottom: 'Sidebar Bottom'
                sidebar-left: 'Sidebar Left'
                sidebar-right: 'Sidebar Right'
                sidebar-top-showcase: 'Sidebar Top with Showcase'
                sidebar-bottom-showcase: 'Sidebar Bottom with Showcase'
                sidebar-left-showcase: 'Sidebar Left with Showcase'
                sidebar-right-showcase: 'Sidebar Right with Showcase'
              help: Select the sidebar location.
            
            header.sidebarpath:
              type: string
              label: Sidebar Content
              default: "/sidebar"
              help: Displays the content of a page in the sidebar.

            header.toc.enabled:
              type: toggle
              default: false
              label: Table of Contents
              highlight: 1
              default: 2
              options:
                0: Use theme setting
                1: Enabled
                2: Disabled
              help: Show or hide the table of contents in the sidebar.

            header.toc.horizontal:
              type: toggle
              default: false
              label: Horizontal Table of Contents (for Sidebar Top/Bottom layout)
              highlight: 1
              default: 0
              options:
                0: Use theme setting
                1: Enabled
                2: Disabled
              help: Displays the table of contents horizontally rather than as a regular list.

          import@:
            type: partials/blog-bits
            context: blueprints://pages

