extends@: default
child_type: item

rules:
  slug:
    pattern: "[a-z][a-z0-9_\-]+"
    min: 2
    max: 80

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        layout:
          type: tab
          title: Layout Settings

          fields:

            content_title:
              type: spacer
              title: Layout Settings

            header.sidebarlayout:
              type: select
              label: Sidebar Layout
              default: default
              options:
                default: 'Sidebar Bottom'
                sidebar-top: 'Sidebar Top'
                sidebar-left-showcase: 'Sidebar Left with Showcase'
                sidebar-right-showcase: 'Sidebar Right with Showcase'
                sidebar-left: 'Sidebar Left'
                sidebar-right: 'Sidebar Right'
              help: Select the sidebar location.
            
            header.sidebarpath:
              type: string
              label: Sidebar Content
              default: "/sidebar"
              help: Displays the content of a page in the sidebar.
            
            header.showcase:
              type: toggle
              default: false
              label: Showcase
              highlight: 1
              default: 1
              options:
                1: Enabled
                0: Disabled
              validate:
                type: bool
              help: Adds a bar with a randomly selected image from the page's folder.

            header.hidetoc:
              type: toggle
              default: false
              label: Table of Contents
              highlight: 0
              default: 0
              options:
                0: Show
                1: Hide
              validate:
                type: bool
              help: Hide the table of contents in the sidebar.

            header.horizontaltoc:
              type: toggle
              default: false
              label: Horizontal Table of Contents (for Sidebar Top/Bottom layout)
              highlight: 1
              default: 0
              options:
                1: Enabled
                0: Disabled
              validate:
                type: bool
              help: Displays the table of contents horizontally rather than as a regular list.

          import@:
            type: partials/blog-bits
            context: blueprints://pages

